# Generated by Django 3.2.4 on 2021-06-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('admission_number', models.IntegerField(unique=True)),
                ('is_qualified', models.BooleanField(default=False)),
                ('average_score', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('student_capacity', models.IntegerField(default=0)),
                ('students', models.ManyToManyField(to='classroom.Student')),
            ],
        ),
    ]
