# Generated by Django 3.2.4 on 2021-06-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_score',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
