# Generated by Django 3.2.4 on 2021-06-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_student_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
